---
# tasks file for ntp

- name: Configuration ntp
  copy:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: '0644'

- name: Redémarrage de ntp
  systemd:
    state: restarted
    name: ntp

...